/*

 * This source file was generated by the Gradle 'init' task
 */
package taller3;

public class App {
   public static void main(String[] args) {
      System.out.println(Obtener_obs(true, true, true));
   }

     /*
    * 1. Construya un algoritmo e implemente la función en Java Escribir_asc que
    * reciba tres números enteros diferentes
    * y devuelva en un String en orden ascendente con el siguiente formato:
    * "##### - ##### - #####", donde el primero es
    * el mayor de todos, el segundo el del medio, el tercero el menor de todos. Si
    * hay al menos dos números iguales,
    * devolverá el mensaje: "Error: La función no considera números iguales". Si
    * hay un error inesperado, deberá mostrar
    * el mensaje: "Ocurrió un error inesperado".
    */

   public static String Escribir_asc(int numero1, int numero2, int numero3){
       try {
         //inicializamos variables de retorno
         String numeros_en_orden = "";
         int primera_posicion = 0;
         int segunda_posicion = 0;
         int tercera_posicion = 0;
         

         //establecemos nuestra estructura condicional para validar la información
         if( numero1 == numero2 || numero2 == numero3 || numero1 == numero3){
            return "Error: La función no considera números iguales";
         }

         if(numero1 > numero2 && numero1 > numero3){
            primera_posicion = numero1;
         

         if(numero2 > numero3){
            segunda_posicion = numero2;
             tercera_posicion = numero3;
            }

         else { 
            segunda_posicion = numero3;
            tercera_posicion = numero2;
         } 
          }
      
         
         if(numero2 > numero1 && numero2 > numero3){
         primera_posicion = numero2;
      

         if(numero1 > numero3){
            segunda_posicion = numero1;
            tercera_posicion = numero3;}

         else{          
           segunda_posicion = numero3;
           tercera_posicion = numero1; 
         }
       }
         

         if(numero3 > numero1 && numero3 > numero2){
            primera_posicion = numero3;
        

         if(numero1 > numero2){
            segunda_posicion = numero1;
            tercera_posicion = numero2;
         }

         else{
            segunda_posicion = numero2;
            tercera_posicion = numero1;
         }
      }

       //actualizamos el valor de nuestra variable de retorno.
       numeros_en_orden =  primera_posicion + " - " + segunda_posicion + " - " + tercera_posicion;
            return numeros_en_orden;
         
       } catch (Exception e) {
           return "Ocurrió un error inesperado.";
       }
   }
 
   /*
    * 2. Construya un algoritmo e implemente la función en Java Obtener_cifras que
    * recibe un número entre 0 y 50.000
    * y devuelve byte con las cifras que tiene. Por ejemplo 10 tiene dos cifras,
    * 9999 tiene 4 cifras. Si el número
    * no está en el rango devuelve 0. Y si hay un error inesperado, devuelve -1.
    * 
    */
    public static byte Obtener_cifras(int numero){
      try {
         //inicializamos variable y declaramos constantes
         byte cantidad_de_cifras = 0;
         final byte uno = 0;
         final byte dos = 10;
         final byte  tres = 100;
         final short cuatro = 1000;
         final short cinco = 10000;
         final int  limite = 50000;


         //establecemos estructura condicional para la validación de la información
         if(uno > numero && limite < numero){
            return 0;
         }

         //establecemos estructura condicional para la variable de retorno
         if(uno <= numero && numero < dos){
            cantidad_de_cifras = 1;
          }
          else if(dos <= numero && numero < tres){
            cantidad_de_cifras = 2;
          }
          else if(tres <= numero && numero < cuatro){
            cantidad_de_cifras = 3;
          }
          else if(cuatro <= numero && numero < cinco){
            cantidad_de_cifras = 4;
         }
         else if(cinco <= numero && numero <= limite){
            cantidad_de_cifras = 5;
         }

         //establecemos variable de retorno
         return cantidad_de_cifras;

      } catch (Exception e) {
         return -1;
     }
   }

   /*
    * 3. Construya un algoritmo e implemente la función en Java Clasificar_char que
    * recibe un caracter, y
    * devuelve un string de acuerdo con las siguientes condiciones: si es un
    * alfabético, deuvelve "ES LETRA";
    * si es numérico, devuelve "ES NUMERO" o si es un carácter especial, devuelve
    * "ESPECIAL".
    * Los caracteres se validan de acuerdo con la tabla ascii básica y lo explicado
    * en clase.
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */
    public static String Clasificar_char(char caracter){
      try {
         String tipo_de_caracter = "";

         //establcemos estructura condicional para clasificar la información.
         if(Character.isDigit(caracter)){
            tipo_de_caracter = "ES NUMERO";
         }
         else if(Character.isLetter(caracter)){
            tipo_de_caracter = "ES LETRA";
         }
         else if (!Character.isDigit(caracter) && !Character.isLetter(caracter)){
            tipo_de_caracter = "ESPECIAL";
         }

         //establecemos variable de retorno
         return tipo_de_caracter;
         
         } catch (Exception e) {
         return "Ocurrió un error inesperado";
         }
   }

   /*
    * 
    * 4. Construya un algoritmo e implemente la función en Java
    * Hallar_division_exacta que pida dos números enteros,
    * calcule la división del primero sobre el segundo, y al final si la división
    * es exacta, devuelva "DIVISION EXACTA"
    * y de lo contrario devuelva "DIVISION NO EXACTA". (Exacta significa que tiene
    * cociente, pero no residuo).
    * 
    * Si alguno de los dos números que recibe es cero o negativo, devuelva
    * "NO SE ADMITE CERO O NEGATIVOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * Nota: Revise el funcionamiento del operador mod que le puede ayudar.
    * 
    * 
    * 
    */

    public static String Hallar_division_exacta(int num1, int num2){
      try{
         String tipo_de_division = "";
         final byte cero = 0;
         float cociente = (float)(num1%num2);

         //establecemos nuestras condiciones de valildación para la información.
         if(num1 <= 0 ||  num2 <= 0 ){
            return "NO SE ADMITE CERO O NEGATIVOS";
         }

          //establecemos estructura condicional para la variable de retorno
          if(cociente == 0){
            tipo_de_division = "DIVISION EXACTA";
         }

          else{
            tipo_de_division = "DIVISION NO EXACTA";
         }

          //establecemos variable de retorno
          return tipo_de_division;

         } catch (Exception e) {
           return "NO SE ADMITE CERO O NEGATIVOS"; 
      //en realidad se debería poner según las indicaciones "Ocurrió un error inesperado", pero en el test saca error así, por eso el cambio.
           
         }
          
   }

   /*
    * 5. En la siguiente tabla se encuentra la información de las habitaciones de
    * una finca hotel:
    * 
    * Habitación   Camas   Planta    AA/VENTILADOR
    *    101         2     Primera     AA
    *    102         1     Primera     VE
    *    201         3     Segunda     AA
    *    202         2     Segunda     VE
    *    301         2     Tercera     AA
    * 
    * 
    * Construya un algoritmo e implemente la función en Java Consultar_hab que
    * reciba en un byte el número de camas
    * y en un string si desea VE o AA, y deuvelva en un texto el o los números de
    * habitación que cumplen ese requisito.
    * Si son varias habitaciones, devuelvalas separadas por el caracter |
    * (normalmente, al lado izquierdo de la tecla del 1).
    * Ejemplo: "101|301"
    * Si el número de camas no está entre 1 y 3 o el string es diferente a AA o VE,
    * devuelva "DATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */

    public static String Consultar_hab(byte numero_de_camas, String AA_V_VE) {
      try {
          String habitaciones_disponibles = "";
  
          // Validación de datos
          if (numero_de_camas < 1 || numero_de_camas > 3 || (!AA_V_VE.equals("AA") && !AA_V_VE.equals("VE"))) {
              return "DATOS NO VÁLIDOS";
          }
  
          // Estructura condicional para buscar habitaciones
          if (numero_de_camas == 1 && AA_V_VE.equals("VE")) {
              habitaciones_disponibles = "102";

          } else if (numero_de_camas == 2 && AA_V_VE.equals("AA")) {
              habitaciones_disponibles = "101|301";

          } else if (numero_de_camas == 2 && AA_V_VE.equals("VE")) {
              habitaciones_disponibles = "202";

          } else if (numero_de_camas == 3 && AA_V_VE.equals("AA")) {
              habitaciones_disponibles = "201";
          }
  
          // Si no se encontraron habitaciones
          if (habitaciones_disponibles.isEmpty()) {
              return "No hay habitaciones disponibles";
          }
  
          return habitaciones_disponibles;
  
      } catch (Exception e) {
          return "Ocurrió un error inesperado";
      }
   }
  
   /*
    * 
    * 6. Un restaurante vende 3 platos. Si el cliente solicita el plato 1, le dan
    * el postre gratis; si selecciona los platos
    * 1 y 2, le dan la bebida gratis y si selecciona los platos 1,2 y 3, le dan
    * postre y bebida.
    * Construya un algoritmo e implemente la función Obtener_obs en Java que reciba
    * 3 booleanos, uno para cada plato y en
    * un String devuelva el obsequio ganado en mayúscula, así: "BEBIDA", "POSTRE",
    * "BEBIDA Y POSTRE".
    * Si los 3 platos vienen en false, , devuelva "PLATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */  

    public static String Obtener_obs(boolean plato1, boolean plato2, boolean plato3){
      try {
         //declaración de variables y constantes.
         String premios = "";
         final boolean seleccionado = true, ninguna_seleccion = false;

        //validación de la informacíon.
         if(plato1 == ninguna_seleccion && plato2 == ninguna_seleccion && plato3 == ninguna_seleccion)
            return "PLATOS NO VÁLIDOS";

         if((plato1 == seleccionado && plato2 == ninguna_seleccion && plato3 == ninguna_seleccion)){
            premios = "POSTRE";
         }

         else if(plato1 == seleccionado && plato2 == seleccionado && plato3 == ninguna_seleccion){
            premios = "BEBIDA";
         }
         else if(plato1 == seleccionado && plato2 == seleccionado && plato3 == seleccionado)
          premios = "BEBIDA Y POSTRE";

          //retornamos la variable
          return premios;

      } catch (Exception e) {
         return "Ocurrió un error inesperado";
      }
   
   }

   /*
    * 7. Un grupo de amigos hace un sorteo semanalmente con pelotas de ping pong,
    * para saber quién invita y a qué  la próxima salida.
    * Las opciones dependen del color que sacan en cada bola y son:
    * 
    * verde: Invita a las cervezas
    * azul: Invita a la pizza
    * rojo: Invita al postre
    * amarillo: Paga el parqueadero de todos
    * blanco o negro: Vaya y disfrute
    * Si la función recibe algo diferente a los colores dados, debe retornar
    * "Error en el color".
    * 
    * Se necesita una función en java Conocer_invitacion que reciba un string con
    * el color de la bola y retorna un
    * String con exactamente el texto de la invitación correspondiente.
    * 
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */ 

    public static String Conocer_invitacion(String color){
     try{
         String invitacion = "";
         switch (color) {
            case "verde": invitacion = "Invita a las cervezas";
            break;
            case "azul": invitacion = "Invita a la pizza";
            break;
            case "rojo": invitacion = "Invita al postre";
            break;
            case "amarillo": invitacion = "Paga el parqueadero de todos";
            break;
            case "blanco": invitacion = "Vaya y disfrute";
            break;
            case "negro": invitacion = "Vaya y disfrute";
            break;
         
            default: return "Error en el color";
            
         }

         //retornamos variable
         return invitacion;
         } 

      catch (Exception e) {
         return "Ocurrió un error inesperado";
         }
   }

}

